//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WpfApp8.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Order
    {
        public string Code { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> id_Client { get; set; }
        public string ProductArticle { get; set; }
        public string Quantity { get; set; }
        public Nullable<int> ManagerId { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Product Product { get; set; }
        public virtual Users Users { get; set; }

        [NotMapped] // Это свойство не будет сохраняться в БД
        public string ManagerFIO => Users != null
        ? $"{Users.Surname} {Users.Name} {Users.Patronymic}"
        : "Не назначен";
        [NotMapped] // Это свойство не будет сохраняться в БД
        public string ClientFIO => Clients != null
        ? $"{Clients.Surname} {Clients.Name} {Clients.Patronymic}"
        : "Клиент не указан";
    }
}
