//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp8.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductArticle { get; set; }
        public string Name { get; set; }
        public Nullable<int> id_Category { get; set; }
        public string Description { get; set; }
        public decimal Cost { get; set; }
        public int QuantityInStock { get; set; }
        public string Measurement { get; set; }
        public Nullable<int> id_Supplier { get; set; }
        public Nullable<int> id_Manufacturer { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
